### ISSUE TITLE
TypeError: Cannot read property 'setCharacteristic' of undefined

### ISSUE THREAD

**Issue by noobydp** [mihailescu2m/homebridge-airtouch4-platform#1]
Hi,
Thanks for creating this, I've wanted to connect to my unit for a long time!

I installed the plugin and used the configuration below. I have a Daikin unit with 3 temp sensors in different rooms.
When I restart homebridge I saw an error in the logs:
TypeError: Cannot read property 'setCharacteristic' of undefined
Which occurred just after creating Zone 0 Thermostat.

I restarted HB a few times and noticed each time it progressed further through the zones and eventually created all 8 zones (0 to 7) so its now working with all the zones setup.

```
[1/17/2020, 2:16:04 PM] [Airtouch] API | Connected to Airtouch
[1/17/2020, 2:16:04 PM] [Airtouch] API | Sending message 68 with type 2d containing:
[1/17/2020, 2:16:04 PM] [Airtouch] <Buffer 01>
[1/17/2020, 2:16:04 PM] [Airtouch] API | Message to send:
[1/17/2020, 2:16:04 PM] [Airtouch] <Buffer 55 55 80 b0 44 2d 00 01 01 cb b9>
[1/17/2020, 2:16:04 PM] [Airtouch] API | Received message with id 68 and data 404298005ce70000
[1/17/2020, 2:16:04 PM] [Airtouch] Received status update for [AC 0]: {"ac_unit_number":0,"ac_power_state":1,"ac_mode":4,"ac_fan_speed":2,"ac_target":24,"ac_temp":24.3,"ac_spill":1,"ac_timer_set":0,"ac_error_code":0}
[1/17/2020, 2:16:04 PM] [Airtouch] [AC 0] was not found, creating as new AC accessory...
HAP Warning: Characteristic 00000029-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.

HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.

HAP Warning: Characteristic 154c4ebb-a16f-488b-8968-2e5bbe15809d not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.

HAP Warning: Characteristic 2f9bfcd0-00ff-481a-873c-188a2e93d316 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.

[1/17/2020, 2:16:04 PM] [Airtouch] Finished creating accessory [AC 0]
[1/17/2020, 2:16:04 PM] [Airtouch] Finished updating accessory [AC 0]
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - connected to TV
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - app launched, current appId: com.webos.app.hdmi2
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - audio status changed
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - current volume: 0
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - muted: No
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - current channel status changed
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - current channel: undefined, undefined
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - sound output changed
[1/17/2020, 2:16:04 PM] [My LG TV] webOS - current sound output: external_speaker
[0;37m[1/17/2020, 2:16:05 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.7.0 is listening on :: port 8124[0m
[1/17/2020, 2:16:06 PM] [TuyaWebPlatform] Adding: Plug Base 6210HA (switch / 48324655c44f33a59b12)
[1/17/2020, 2:16:06 PM] [TuyaWebPlatform] Existing Accessory found [Plug Base 6210HA] [48324655c44f33a59b12] [b215c4c0-3609-419b-8170-ca48ce0c118c]
[1/17/2020, 2:16:06 PM] [Airtouch] API | Sending message 246 with type 2b containing:
[1/17/2020, 2:16:06 PM] [Airtouch] <Buffer 01>
[1/17/2020, 2:16:06 PM] [Airtouch] API | Message to send:
[1/17/2020, 2:16:06 PM] [Airtouch] <Buffer 55 55 80 b0 f6 2b 00 01 01 59 81>
[1/17/2020, 2:16:06 PM] [Airtouch] API | Received message with id 246 and data 408018e45b9701641e00ffe742e418e45ce7038018805d6004640400ffe705640400ffe706640400ffe707281500ffe7
[1/17/2020, 2:16:06 PM] [Airtouch] Received status update for [Zone 0]: {"group_number":0,"group_power_state":1,"group_control_type":1,"group_damper_position":0,"group_target":24,"group_temp":23.2,"group_battery_low":0,"group_has_turbo":0,"group_has_sensor":1,"group_has_spill":1}
[1/17/2020, 2:16:06 PM] [Airtouch] [Zone 0] was not found, creating as new Zone accessory...
[1/17/2020, 2:16:06 PM] [Airtouch] Finished creating accessory [Zone 0]
HAP Warning: Characteristic 000000B0-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.

[1/17/2020, 2:16:06 PM] [Airtouch] Updating [Zone 0 Thermostat]
[1/17/2020, 2:16:06 PM] [Airtouch] [Zone 0 Thermostat] was not found, creating as new Thermostat accessory...
[1/17/2020, 2:16:06 PM] [Airtouch] Finished creating accessory [Zone 0 Thermostat]
[1/17/2020, 2:16:06 PM] [Airtouch] Finished updating accessory [Zone 0 Thermostat]
[1/17/2020, 2:16:06 PM] TypeError: Cannot read property 'setCharacteristic' of undefined
at Airtouch.updateZoneAccessory (/usr/lib/node_modules/homebridge-airtouch4-platform/index.js:421:14)
at /usr/lib/node_modules/homebridge-airtouch4-platform/index.js:143:8
at Array.forEach (<anonymous>)
at Airtouch.onGroupsStatusNotification (/usr/lib/node_modules/homebridge-airtouch4-platform/index.js:125:16)
at AirtouchAPI.<anonymous> (/usr/lib/node_modules/homebridge-airtouch4-platform/index.js:65:8)
at AirtouchAPI.emit (events.js:210:5)
at AirtouchAPI.decode_groups_status (/usr/lib/node_modules/homebridge-airtouch4-platform/api.js:264:7)
at Socket.<anonymous> (/usr/lib/node_modules/homebridge-airtouch4-platform/api.js:304:10)
at Socket.emit (events.js:210:5)
at emitReadable_ (_stream_readable.js:574:12)
[1/17/2020, 2:16:06 PM] Got SIGTERM, shutting down Homebridge...
```

```
{
            "platform": "Airtouch",
            "name": "Airtouch",
            "ip_address": "192.168.1.242",
            "ac_include_temps": true,
            "units": [
                {
                    "manufacturer": "Daikin",
                    "model": "UNIT1",
                    "fan": [
                        "AUTO",
                        "LOW",
                        "MEDIUM",
                        "HIGH"
                    ]
                }
            ]
        }
```

**Comment by mihailescu2m** [comment]
Yes I found the bug, will fix it in a next release.

Unrelated: do you use the temperature control or the damper control?
Personally I use the damper control more, and with a thermostat for each zone for the temperature control I noticed Siri sometimes gets confused - e.g. there are 2 thermostats in the living-room (one for the AC unit, and one for the Zone) and sometimes gets commands mixed. So I was thinking of adding an option to enable/disable temperature control (with temp control disabled, you only get one thermostat, for the AC, and only damper controls for zones).

**Comment by noobydp** [comment]
Awesome. 

I mainly use the temp controls in the rooms that have the remote units. Only sometimes I use the damper if I need an extra boost. 

I put my AC unit in a completely separate room in the home app so it only ever looks at the temp from the remote.

**Comment by mihailescu2m** [comment]
I see.

I have given up on the temperature control because of this scenario (last winter):
I have the touchpad set as the sensor, which is in the living room. The bedrooms are smaller and better insulated, so they heat/cool faster than the living room.
With the damper control, I found some settings for the dampers where they roughly maintain the temperature I want for the other rooms. For example, if I set it on heat, e.g. to 19C at the AC, and set the bedroom damper to 80%, it will roughly maintain the bedroom temperature at 21-22C (which is what I want).
But, if I set the bedroom to temperature control to 21C, then it will actually move the AC temperature from 19C to 21C (AC temperature is set as the max of rooms for heat, and min for cool), which means that it will turn up the living temp to 21C as well and use more power than it needs to. Is this something that you noticed too?

**Comment by noobydp** [comment]
Yeah mine does the same and my living room ends up being too hot because it’s also the spill zone. 
It’s mostly noticeable when I’m cooling because for some reason it keeps cooling for too long. My rooms hit 23 deg but my living room can hit 21. 

One of the ac guys told me not to use the tablet as a sensor because it can get warm and mine isn’t in a good place, so I end up using a remote in my living and changed some settings to disable the touch pad thermometer. 

You could also try a different setting which affects what the AC does with different temps. The AC measured temp in my case is the temp of the return air. 
The setting is in: System Settings > Installers > AC Setup > Detail Settings > Control Sensor
Mines currently on Economy which is ok but not great, better than Auto. 

The installer password should be 8 spaces. 

Also out of curiosity, how’d you decode the data that’s sent to the unit to control the features? I used some network monitoring tools to capture the data and managed to copy some of the requests, but didn’t get far in understanding the values.

**Comment by mihailescu2m** [comment]
I had mine set on the return air initially, which worked so-so in winter, but on hot/summer days it was really bad, since the roof got hot - the AC unit is on top of the insulation, so the return air sensor was showing close to 30C but in the house it was much cooler. I think AUTO/ECONOMY uses the return air sensor (AC) and not the rooms sensors. So I ended up setting it to touchpad...

The protocol I got from Polyaire, they are actually based in ADL (same) and after I sent them an email they sent a document with all the fields :) pretty cool.

**Comment by noobydp** [comment]
Ah ok i might have different readings because my return and ac unit are
fairly well covered in the summer.

I was wondering if they'd send me the specs. It is pretty cool they
shared it.
I was looking at my zone controller board and there's actually a rj12 port
labelled "Homekit". I checked with them but they never produced the module
:cry:

**Comment by ghost** [comment]
I've only had my unit installed for 4 months so haven't had any experience heating here in Syd, but think I'm having similar experiences with cooling (freezing my kids in their beds). 
Using the airtouch system to set all rooms (with individual sensors) to 24deg, the kids room was getting down to 22deg while mine was still hanging around 26deg. 
I was looking to this plugin to have better control over the dampers, with a set temp - say 24deg - and kids rooms at 25% while my bigger master room is at 100%. Also opportunity to vary the dampers based on temp differentials - i.e. turbo cooling/heating before bedtime.
I too spotted the 'HomeKit' port in the user guide and got excited... Considering they've related the protocol to you, they might be looking to you for a software based solution ;-)

**Comment by noobydp** [comment]
I had someone come look at mine was told you need to have one zone without a temperature sensor. I removed the temp sensor from the spill zone which is my main lounge, and adjust the damper speed to control the room temp. 

Apparently having a zone without the temp sensor causes the system to obey the return air temperature. 
If all the temp sensors and the return air are at the set temp, the cooler unit will shut down. 

The rooms also turn on / off as per their set temp.

**Comment by noobydp** [comment]
I’m going to close this issue, don’t think there’s much we can do with this software unless you could somehow build logic to control rooms.

**Comment by mihailescu2m** [comment]
Logic can be done from the home app (via automation). Even better from the Eve app (eg I added darksky for outside conditions and forecast and use that plus inside temps)
